import { p, type Note } from "../../lib/content-types";

// Análisis AN01. Fuentes comprobadas el 25/09/2026:
// - Obligaciones y artículos: Reglamento (UE) 2024/1689 (EUR-Lex).
// - Calendario y cambios de 2026: Reglamento (UE) 2026/1744 (EUR-Lex) y Gibson Dunn.
// - ONU: nota de prensa SG/SM/23292 (Guterres, 22/09/2026); Costa (24/09/2026); Trump (22/09/2026, Scientific American);
//   Altman y Amodei ante el Consejo de Seguridad (23/09/2026, CNN); Kratsios (septiembre de 2025, NBC).
// - Casos: peticiones de información (Agence Europe, 2/09/2026); Grok (Al Jazeera, 26/01/2026; Irish Times, 17/02/2026).
// - Datos: gráficos de la nota N02 (Eurostat isoc_eb_ai).
// Se descartaron las "primeras multas" de agosto de 2026 que circulan en algunas webs: no aparecen en fuentes oficiales.

const t = (es: string, en: string) => ({ es, en });

const note: Note = {
  id: "an01",
  kind: "analisis",
  code: "AN01",
  slug: { es: "ai-act-como-cumplirlo", en: "ai-act-how-to-comply" },
  title: {
    es: "Cómo se cumple el AI Act: obligaciones, costes y la batalla política por regular la IA",
    en: "How to comply with the AI Act: obligations, costs and the political battle over regulating AI",
  },
  dek: {
    es: "Una guía práctica de la ley europea de inteligencia artificial tras su reforma de 2026: qué exige a cada empresa, en qué orden hay que hacer las cosas, qué problemas está dando, qué se ha visto ya en la práctica y por qué la ONU, Washington y Pekín la miran de forma tan distinta.",
    en: "A practical guide to the European AI law after its 2026 reform: what it requires of each company, in what order to act, the problems it is causing, what has already happened in practice and why the UN, Washington and Beijing see it so differently.",
  },
  published: "2026-09-25",
  lens: "elige",
  theme: "ia-digital",
  body: [
    { h: t("Qué es y a quién obliga", "What it is and who it applies to"), id: "que-es" },
    p("El AI Act (Reglamento (UE) 2024/1689) regula los sistemas de inteligencia artificial según el riesgo que suponen, no según la tecnología que usan. No se aplica solo a las empresas europeas: obliga a cualquier proveedor que venda o ponga en servicio un sistema de IA en la UE, y también cuando el resultado del sistema se utiliza en la UE, aunque la empresa esté fuera.",
      "The AI Act (Regulation (EU) 2024/1689) regulates artificial intelligence systems according to the risk they pose, not the technology they use. It does not only apply to European companies: it binds any provider that sells or puts into service an AI system in the EU, and also applies when the system's output is used in the EU, even if the company is based elsewhere."),
    p("Lo primero que tiene que saber una empresa es qué papel juega, porque las obligaciones cambian mucho según el papel:",
      "The first thing a company needs to know is its role, because obligations change a great deal depending on it:"),
    { list: [
      t("Proveedor: quien desarrolla el sistema o el modelo, o lo encarga, y lo comercializa con su nombre. Carga con la mayor parte de las obligaciones.",
        "Provider: whoever develops the system or model, or has it developed, and markets it under its own name. It bears most of the obligations."),
      t("Responsable del despliegue: la empresa u organismo que usa un sistema de IA en su actividad, por ejemplo un banco que usa un modelo de scoring comprado a otro.",
        "Deployer: the company or body that uses an AI system in its activity, for example a bank using a scoring model bought from someone else."),
      t("Importador y distribuidor: quienes lo traen a la UE o lo revenden. Deben comprobar que el proveedor ha cumplido.",
        "Importer and distributor: those who bring it into the EU or resell it. They must check that the provider has complied."),
      t("Cuidado con el cambio de papel: quien pone su marca a un sistema de alto riesgo, lo modifica de forma sustancial o lo usa para un fin de alto riesgo distinto del previsto pasa a ser proveedor (artículo 25).",
        "Watch out for a change of role: whoever puts their brand on a high-risk system, substantially modifies it or uses it for a different high-risk purpose becomes a provider (Article 25)."),
    ] },

    { h: t("Cuatro niveles de riesgo y los modelos de propósito general", "Four risk levels and general-purpose models"), id: "niveles" },
    { list: [
      t("Prohibido (artículo 5). Manipulación que distorsiona el comportamiento, explotación de vulnerabilidades, puntuación social, predicción policial individual basada solo en perfiles, bases de reconocimiento facial creadas raspando imágenes de forma indiscriminada, reconocimiento de emociones en el trabajo y en la educación, categorización biométrica por datos sensibles e identificación biométrica remota en tiempo real en espacios públicos por la policía, salvo excepciones tasadas. La reforma de 2026 añade los sistemas que generan imágenes íntimas no consentidas o material de abuso sexual infantil.",
        "Prohibited (Article 5). Manipulation that distorts behaviour, exploitation of vulnerabilities, social scoring, individual predictive policing based solely on profiling, facial recognition databases built by untargeted scraping, emotion recognition at work and in education, biometric categorisation by sensitive data and real-time remote biometric identification in public spaces by police, save for narrow exceptions. The 2026 reform adds systems that generate non-consensual intimate images or child sexual abuse material."),
      t("Alto riesgo (artículo 6). La IA que forma parte de productos ya regulados (máquinas, productos sanitarios, juguetes...) y la que se usa en los ámbitos del anexo III: biometría, infraestructuras críticas, educación, empleo y gestión de trabajadores, acceso a servicios esenciales como el crédito o los seguros, policía, migración y fronteras, y justicia y procesos democráticos.",
        "High risk (Article 6). AI that is part of already regulated products (machinery, medical devices, toys...) and AI used in the Annex III areas: biometrics, critical infrastructure, education, employment and worker management, access to essential services such as credit or insurance, law enforcement, migration and borders, and justice and democratic processes."),
      t("Transparencia (artículo 50). Los chatbots deben avisar de que son una máquina; el contenido generado por IA debe marcarse de forma legible por máquinas, y los deepfakes, etiquetarse.",
        "Transparency (Article 50). Chatbots must disclose that they are machines; AI-generated content must be marked in a machine-readable way, and deepfakes labelled."),
      t("Riesgo mínimo. El resto, que es la mayoría de usos (filtros de spam, recomendadores, herramientas internas), no tiene obligaciones específicas.",
        "Minimal risk. Everything else, which is most uses (spam filters, recommenders, internal tools), has no specific obligations."),
    ] },
    p("Un sistema del anexo III puede quedar fuera del alto riesgo si no plantea un riesgo significativo: por ejemplo, si solo hace una tarea procedimental limitada o prepara una evaluación que después hace una persona. Pero la excepción nunca vale si el sistema elabora perfiles de personas, y el proveedor debe documentar por qué la aplica y registrar el sistema.",
      "An Annex III system can fall outside high risk if it poses no significant risk: for example, if it only performs a narrow procedural task or prepares an assessment later made by a person. But the exception never applies if the system profiles people, and the provider must document why it applies it and register the system."),
    p("Los modelos de propósito general, como los grandes modelos de lenguaje, tienen reglas propias: documentación técnica, información para quienes construyen sobre ellos, una política de respeto a los derechos de autor y un resumen público de los datos de entrenamiento. Si se entrenaron con más de 10²⁵ operaciones de cálculo, se presume que tienen riesgo sistémico y deben además evaluar y mitigar ese riesgo, hacer pruebas adversarias, notificar incidentes graves y proteger su ciberseguridad. Un código de buenas prácticas voluntario, publicado en julio de 2025, sirve para demostrar el cumplimiento; Meta anunció entonces que no lo firmaría.",
      "General-purpose models, such as large language models, have their own rules: technical documentation, information for those building on them, a copyright policy and a public summary of training data. If trained with more than 10²⁵ floating-point operations, they are presumed to pose systemic risk and must also assess and mitigate that risk, run adversarial testing, report serious incidents and protect their cybersecurity. A voluntary code of practice, published in July 2025, serves to demonstrate compliance; Meta announced at the time that it would not sign it."),

    { h: t("El calendario, tras la reforma de 2026", "The timeline, after the 2026 reform"), id: "calendario" },
    { timeline: [
      { date: t("1 ago. 2024", "1 Aug 2024"), text: t("Entra en vigor el AI Act.", "The AI Act enters into force.") },
      { date: t("2 feb. 2025", "2 Feb 2025"), text: t("Se aplican las prohibiciones.", "Prohibitions apply.") },
      { date: t("2 ago. 2025", "2 Aug 2025"), text: t("Obligaciones de los modelos de propósito general.", "Obligations for general-purpose models.") },
      { date: t("27 jul. 2026", "27 Jul 2026"), text: t("Entra en vigor la reforma (Reglamento (UE) 2026/1744), que aplaza las obligaciones de alto riesgo.", "The reform (Regulation (EU) 2026/1744) enters into force, postponing high-risk obligations.") },
      { date: t("2 ago. 2026", "2 Aug 2026"), text: t("La Comisión puede exigir información, evaluar modelos y multar a los proveedores de modelos. Se aplican las obligaciones de transparencia.", "The Commission can demand information, evaluate models and fine model providers. Transparency obligations apply.") },
      { date: t("2 dic. 2026", "2 Dec 2026"), text: t("Nuevas prohibiciones (imágenes íntimas no consentidas y abuso infantil) y fin del periodo de gracia para marcar el contenido de sistemas ya en el mercado.", "New prohibitions (non-consensual intimate images and child abuse) and end of the grace period for marking content from systems already on the market.") },
      { date: t("2 dic. 2027", "2 Dec 2027"), text: t("Obligaciones de alto riesgo del anexo III (antes, agosto de 2026).", "Annex III high-risk obligations (previously August 2026).") },
      { date: t("2 ago. 2028", "2 Aug 2028"), text: t("Obligaciones de alto riesgo de la IA integrada en productos regulados (antes, agosto de 2027).", "High-risk obligations for AI built into regulated products (previously August 2027).") },
    ] },

    { h: t("Cómo cumplir, paso a paso", "How to comply, step by step"), id: "como-cumplir" },
    p("Para la mayoría de empresas, que usan IA comprada a otros, el trabajo es sobre todo de inventario, clasificación y control. Las obligaciones técnicas pesadas recaen en quien desarrolla sistemas de alto riesgo. Este es el orden razonable:",
      "For most companies, which use AI bought from others, the work is mostly inventory, classification and control. The heavy technical obligations fall on those who develop high-risk systems. This is a sensible order:"),
    { steps: [
      { title: t("Inventario.", "Inventory."), text: t("Lista todos los sistemas de IA que usa o vende la organización, incluidos los que vienen dentro de software de terceros y los que los empleados usan por su cuenta.", "List every AI system the organisation uses or sells, including those embedded in third-party software and those employees use on their own.") },
      { title: t("Clasificación.", "Classification."), text: t("Para cada uso, decide si está prohibido, es de alto riesgo, tiene obligaciones de transparencia o es de riesgo mínimo. Documenta el razonamiento, sobre todo si aplicas la excepción del anexo III.", "For each use, decide whether it is prohibited, high-risk, subject to transparency or minimal risk. Document the reasoning, especially if you rely on the Annex III exception.") },
      { title: t("Prohibidos, fuera.", "Prohibited uses out."), text: t("Retira cualquier uso prohibido: se aplican desde febrero de 2025 y tienen las multas más altas.", "Remove any prohibited use: the bans have applied since February 2025 and carry the highest fines.") },
      { title: t("Papel y contratos.", "Role and contracts."), text: t("Determina si eres proveedor o responsable del despliegue en cada caso y exige a tus proveedores la documentación, las instrucciones de uso y el compromiso de cumplimiento por contrato.", "Determine whether you are provider or deployer in each case, and require your suppliers to provide documentation, instructions for use and a contractual compliance commitment.") },
      { title: t("Si desarrollas alto riesgo.", "If you develop high-risk AI."), text: t("Necesitas un sistema de gestión de riesgos durante todo el ciclo de vida (artículo 9), gobernanza de los datos de entrenamiento con análisis de sesgos (artículo 10), documentación técnica según el anexo IV (artículo 11), registro automático de eventos (artículo 12), instrucciones claras (artículo 13), diseño para la supervisión humana (artículo 14), precisión, robustez y ciberseguridad (artículo 15) y un sistema de gestión de la calidad (artículo 17).", "You need a risk management system across the whole life cycle (Article 9), governance of training data including bias analysis (Article 10), technical documentation per Annex IV (Article 11), automatic event logging (Article 12), clear instructions (Article 13), design for human oversight (Article 14), accuracy, robustness and cybersecurity (Article 15) and a quality management system (Article 17).") },
      { title: t("Evaluación de conformidad y registro.", "Conformity assessment and registration."), text: t("La mayoría de sistemas del anexo III se autoevalúan con control interno; los biométricos pueden necesitar un organismo notificado. Después, declaración UE de conformidad, marcado CE y registro en la base de datos de la UE.", "Most Annex III systems are self-assessed through internal control; biometric ones may need a notified body. Then an EU declaration of conformity, CE marking and registration in the EU database.") },
      { title: t("Si usas alto riesgo.", "If you use high-risk AI."), text: t("Úsalo según las instrucciones, asigna la supervisión a personas formadas, vigila los datos de entrada, guarda los registros al menos seis meses, informa a los trabajadores y a sus representantes antes de usarlo en el trabajo y avisa a las personas afectadas por sus decisiones. Los organismos públicos y quienes evalúan el crédito o fijan precios de seguros de vida y salud deben hacer además una evaluación de impacto en los derechos fundamentales (artículo 27).", "Use it according to the instructions, assign oversight to trained people, monitor input data, keep logs for at least six months, inform workers and their representatives before using it at work and tell affected people about its decisions. Public bodies and those assessing creditworthiness or pricing life and health insurance must also carry out a fundamental rights impact assessment (Article 27).") },
      { title: t("Transparencia.", "Transparency."), text: t("Revisa chatbots, generadores de texto, imagen o voz y cualquier contenido sintético: aviso al usuario, marcado técnico y etiqueta en los deepfakes.", "Review chatbots, text, image or voice generators and any synthetic content: user notice, technical marking and labels on deepfakes.") },
      { title: t("Vigilancia continua.", "Ongoing monitoring."), text: t("Los proveedores de alto riesgo deben seguir el sistema tras su lanzamiento y notificar los incidentes graves a la autoridad, como tarde en 15 días desde que los conocen.", "High-risk providers must monitor the system after launch and report serious incidents to the authority no later than 15 days after becoming aware of them.") },
    ] },
    p("Las multas se escalonan según la gravedad: hasta 35 millones de euros o el 7 % de la facturación mundial por usos prohibidos; hasta 15 millones o el 3 % por incumplir otras obligaciones, y hasta 7,5 millones o el 1 % por dar información incorrecta. Se aplica la cifra más alta, salvo a las pymes, a las que se aplica la más baja. Los proveedores de modelos de propósito general se enfrentan a multas de hasta 15 millones o el 3 %.",
      "Fines are tiered by severity: up to 35 million euros or 7% of worldwide turnover for prohibited uses; up to 15 million or 3% for breaching other obligations; and up to 7.5 million or 1% for supplying incorrect information. The higher figure applies, except for SMEs, where the lower one does. Providers of general-purpose models face fines of up to 15 million or 3%."),

    { h: t("Problemas y ventajas", "Problems and advantages"), id: "problemas-ventajas" },
    p("El principal problema es la incertidumbre. Las normas técnicas armonizadas, que son las que permiten presumir que un sistema cumple, no estaban terminadas a tiempo, y varios países tardaron en designar a sus autoridades de supervisión. Esas dos razones explican el aplazamiento de 2026. Las propias empresas lo notan: entre las que se plantearon usar IA y no lo hicieron, la falta de claridad sobre las consecuencias legales pasó del 46 % en 2023 al 54 % en 2025, y ya es el segundo freno, solo por detrás de la falta de conocimientos.",
      "The main problem is uncertainty. The harmonised technical standards, which allow a presumption that a system complies, were not finished in time, and several countries were slow to designate their supervisory authorities. Those two reasons explain the 2026 postponement. Companies notice it themselves: among those that considered using AI but did not, unclear legal consequences rose from 46% in 2023 to 54% in 2025 and are now the second barrier, behind only a lack of expertise."),
    { fig: "n02-ia-frenos", code: "N02-1" },
    { list: [
      t("Problemas: coste de cumplimiento para pymes y startups, solapamiento con el reglamento de protección de datos, la Ley de Servicios Digitales y las normas sectoriales, riesgo de que cada país lo aplique a su manera y calendario cambiante, que castiga a quien ya había invertido para llegar a 2026.",
        "Problems: compliance costs for SMEs and start-ups, overlap with data protection rules, the Digital Services Act and sectoral rules, the risk that each country applies it differently, and a shifting timeline that penalises those who had already invested to meet 2026."),
      t("Ventajas: una sola norma para 27 mercados en lugar de 27 leyes distintas, protección de derechos que ya funciona en lo prohibido, más confianza de clientes y administraciones, y un estándar que puede servir de referencia a otras jurisdicciones y a las grandes empresas que venden en todo el mundo.",
        "Advantages: one rulebook for 27 markets instead of 27 different laws, rights protection already working for prohibited uses, more trust from customers and public bodies, and a standard that can serve as a reference for other jurisdictions and for large companies selling worldwide."),
    ] },
    p("La subida de la incertidumbre es general: afecta a 17 de los 18 países con datos de 2023 y 2025. La encuesta de Eurostat no distingue entre leyes, así que no todo se puede atribuir al AI Act.",
      "The rise in uncertainty is widespread: it affects 17 of the 18 countries with data for 2023 and 2025. The Eurostat survey does not distinguish between laws, so not all of it can be attributed to the AI Act."),
    { fig: "n02-ia-incertidumbre-legal", code: "N02-2" },

    { h: t("La batalla política: lo que se dijo en la ONU", "The political battle: what was said at the UN"), id: "onu" },
    p("La Asamblea General de la ONU, cuyo debate general empezó el 22 de septiembre de 2026, ha escenificado tres formas de ver la regulación de la IA.",
      "The UN General Assembly, whose general debate began on 22 September 2026, staged three ways of seeing AI regulation."),
    p("El secretario general, António Guterres, dedicó a la IA una parte central de su último discurso ante la Asamblea. Pidió que los países que lideran la tecnología cooperen en la evaluación de los sistemas, compartan información sobre riesgos y acuerden salvaguardas comunes, apoyándose en el Panel Científico Internacional sobre IA, que presentó su primer informe en julio, y en el Diálogo Global sobre Gobernanza de la IA, reunido en Ginebra ese mismo mes.",
      "Secretary-General António Guterres devoted a central part of his last address to the Assembly to AI. He asked the countries leading the technology to cooperate on evaluating systems, share information on risks and agree common safeguards, drawing on the Independent International Scientific Panel on AI, which presented its first report in July, and the Global Dialogue on AI Governance, which met in Geneva that same month."),
    { quote: t("«La inteligencia artificial debe ser moldeada por la humanidad, con la humanidad y para toda la humanidad».", "“Artificial intelligence must be shaped by humanity, with humanity and for all humanity.”"),
      who: t("António Guterres, secretario general de la ONU, 22 de septiembre de 2026", "António Guterres, UN Secretary-General, 22 September 2026"),
      url: "https://press.un.org/en/2026/sgsm23292.doc.htm" },
    p("Estados Unidos fue en la dirección contraria. El presidente Donald Trump dijo ante la Asamblea que su país rechaza cualquier intento de construir un «plan globalista» para controlar la IA, y que seguirá liderando lo que llamó superinteligencia. Es la misma línea que un año antes defendió en el Consejo de Seguridad su asesor científico, Michael Kratsios, al rechazar «todos los esfuerzos» de organismos internacionales por gobernar la IA.",
      "The United States went the other way. President Donald Trump told the Assembly that his country rejects any attempt to build a “globalist scheme” to control AI, and that it will keep leading what he called superintelligence. It is the same line his science adviser, Michael Kratsios, took at the Security Council a year earlier when rejecting “all efforts” by international bodies to govern AI."),
    p("La paradoja llegó al día siguiente, el 23 de septiembre, en el Consejo de Seguridad: los consejeros delegados de OpenAI, Sam Altman, y de Anthropic, Dario Amodei, pidieron estándares internacionales. Altman propuso normas comunes para medir capacidades, evaluar riesgos y preservar la supervisión humana. Amodei planteó acuerdos globales acotados, como prohibir el uso de la IA para fabricar armas biológicas, sistemas para verificar compromisos entre países y un mecanismo común de notificación de incidentes.",
      "The paradox came the next day, 23 September, at the Security Council: the chief executives of OpenAI, Sam Altman, and Anthropic, Dario Amodei, asked for international standards. Altman proposed common rules to measure capabilities, assess risks and preserve human oversight. Amodei suggested narrow global agreements, such as banning the use of AI to make biological weapons, systems to verify commitments between countries and a common incident notification mechanism."),
    p("La UE habló el 24 de septiembre por boca del presidente del Consejo Europeo, António Costa, que defendió una gobernanza de la IA «responsable, transparente y regulada» y un papel central para la ONU. China, por su parte, ha creado su propio foro: en julio de 2026 impulsó la Organización Mundial de Cooperación en Inteligencia Artificial.",
      "The EU spoke on 24 September through European Council President António Costa, who called for AI governance that is “responsible, transparent and regulated” and a central role for the UN. China, for its part, has created its own forum: in July 2026 it launched the World Artificial Intelligence Cooperation Organization."),
    { quote: t("«La industria de la IA no puede ser regulada por unas pocas grandes empresas globales».", "“The AI industry cannot be regulated by a few large global companies.”"),
      who: t("António Costa, presidente del Consejo Europeo, 24 de septiembre de 2026", "António Costa, President of the European Council, 24 September 2026"),
      url: "https://www.democrata.es/en/international/costa-alerts-the-un-about-the-power-of-tech-companies-ai-cannot-be-regulated-by-a-few-large-companies/" },
    p("El resultado es incómodo para Europa. Tiene la única ley general de IA en vigor y la ONU mira en su dirección, pero el país que concentra la mayor parte de los modelos más avanzados rechaza cualquier marco internacional, y la propia UE acaba de aplazar la parte más exigente de su ley. Europa ha elegido regular; ahora tiene que demostrar que puede hacerlo sin quedarse aún más atrás.",
      "The outcome is awkward for Europe. It has the only general AI law in force and the UN looks in its direction, but the country home to most of the most advanced models rejects any international framework, and the EU itself has just postponed the most demanding part of its law. Europe has chosen to regulate; now it has to show it can do so without falling further behind."),

    { h: t("Casos recientes", "Recent cases"), id: "casos" },
    { list: [
      t("Primeras peticiones de información. Desde el 2 de agosto de 2026, la Comisión puede actuar contra los proveedores de modelos. A finales de agosto envió sus primeras peticiones de información a más de 30 proveedores, en dos líneas: la seguridad de los modelos más avanzados y los derechos de autor y la transparencia sobre los datos de entrenamiento. Según la vicepresidenta Henna Virkkunen, iban dirigidas a empresas que no habían participado en los diálogos informales con la Oficina de IA.",
        "First requests for information. Since 2 August 2026 the Commission can act against model providers. At the end of August it sent its first requests for information to more than 30 providers, along two lines: the safety of the most advanced models, and copyright and transparency about training data. According to Executive Vice-President Henna Virkkunen, they targeted companies that had not taken part in informal dialogues with the AI Office."),
      t("Grok y los deepfakes sexuales. En enero de 2026, la Comisión abrió un procedimiento contra X por la función de Grok que permitía crear imágenes sexuales falsas de personas reales, incluidas menores. Se hizo con la Ley de Servicios Digitales, no con el AI Act, y en febrero la autoridad irlandesa de protección de datos abrió su propia investigación. La reforma del AI Act aprobada meses después prohíbe expresamente estos sistemas desde diciembre de 2026.",
        "Grok and sexual deepfakes. In January 2026, the Commission opened proceedings against X over the Grok feature that allowed users to create fake sexual images of real people, including minors. It did so under the Digital Services Act, not the AI Act, and in February the Irish data protection authority opened its own investigation. The AI Act reform adopted months later expressly bans such systems from December 2026."),
      t("El propio aplazamiento. La reforma de 2026 es en sí un caso de ejecución: la UE reconoció que ni las normas técnicas ni las autoridades nacionales estaban listas y retrasó 16 meses la fecha clave para la IA de alto riesgo.",
        "The postponement itself. The 2026 reform is an enforcement case in its own right: the EU acknowledged that neither technical standards nor national authorities were ready and pushed back the key date for high-risk AI by 16 months."),
      t("Cuidado con las «primeras multas». Circulan por internet cifras de multas del AI Act supuestamente impuestas en agosto de 2026 a empresas de selección de personal, crédito o comercio. No hemos encontrado ninguna confirmada por la Comisión ni por una autoridad nacional, y algunas son imposibles: las obligaciones de alto riesgo que citan no se aplican hasta diciembre de 2027.",
        "Beware of the “first fines”. Figures circulate online for AI Act fines allegedly imposed in August 2026 on recruitment, credit or retail companies. We have not found any confirmed by the Commission or a national authority, and some are impossible: the high-risk obligations they cite do not apply until December 2027."),
    ] },
    p("Para una empresa española, la autoridad de referencia es la Agencia Española de Supervisión de la Inteligencia Artificial (AESIA), con sede en A Coruña. La recomendación práctica es no esperar a 2027: el inventario, la clasificación y las cláusulas con proveedores se pueden hacer hoy, y son lo que más cuesta improvisar.",
      "For a Spanish company, the reference authority is the Spanish Agency for the Supervision of Artificial Intelligence (AESIA), based in A Coruña. The practical advice is not to wait for 2027: the inventory, the classification and the supplier clauses can be done today, and they are the hardest things to improvise."),
  ],
  sources: [
    { name: "EUR-Lex: Reglamento (UE) 2024/1689 (AI Act)", url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj" },
    { name: "EUR-Lex: Reglamento (UE) 2026/1744 (Digital Omnibus on AI)", url: "https://eur-lex.europa.eu/eli/reg/2026/1744/oj/eng" },
    { name: "Gibson Dunn: EU AI Act Omnibus Agreement, postponed high-risk deadlines", url: "https://www.gibsondunn.com/eu-ai-act-omnibus-agreement-postponed-high-risk-deadlines-and-other-key-changes/" },
    { name: "ONU: discurso del secretario general en la apertura del debate general (22/09/2026)", url: "https://press.un.org/en/2026/sgsm23292.doc.htm" },
    { name: "Scientific American: Trump rejects AI regulation in U.N. address (22/09/2026)", url: "https://www.scientificamerican.com/article/trump-rejects-ai-regulation-citing-parallels-with-climate-change-in-un-address/" },
    { name: "CNN: Altman y Amodei ante el Consejo de Seguridad (23/09/2026)", url: "https://www.cnn.com/2026/09/23/tech/altman-amodei-ai-safety-un-security-council" },
    { name: "Demócrata: discurso de António Costa en la ONU (24/09/2026)", url: "https://www.democrata.es/en/international/costa-alerts-the-un-about-the-power-of-tech-companies-ai-cannot-be-regulated-by-a-few-large-companies/" },
    { name: "NBC News: EE. UU. rechaza la supervisión internacional de la IA (septiembre de 2025)", url: "https://www.nbcnews.com/tech/tech-news/us-rejects-international-ai-oversight-un-general-assembly-rcna233478" },
    { name: "ONU: Panel Científico Internacional sobre IA, informe preliminar", url: "https://www.un.org/independent-international-scientific-panel-ai/en/preliminary-report" },
    { name: "Ministerio de Asuntos Exteriores de China: declaración de la Conferencia Mundial de IA 2026", url: "https://www.mfa.gov.cn/mfa_eng/xw/zyxw/202607/t20260717_11984715.html" },
    { name: "Agence Europe: primeras peticiones de información a más de 30 proveedores de IA (2/09/2026)", url: "https://agenceurope.eu/en/bulletin/article/13929/31/european-commission-sends-first-requests-for-information-to-more-than-30-ai-providers" },
    { name: "Al Jazeera: la UE investiga la función de Grok (26/01/2026)", url: "https://www.aljazeera.com/amp/news/2026/1/26/eu-launches-probe-into-grok-ai-feature-creating-deepfakes-of-women-minors" },
    { name: "The Irish Times: la DPC investiga a X por Grok (17/02/2026)", url: "https://www.irishtimes.com/business/2026/02/17/dpc-investigates-x-over-potential-breaches-linked-to-nudification-of-images-via-grok/" },
  ],
};

export default note;
